package store

// The one place SQLite and Postgres differ (claude-fleet#2120, EPIC #2119 C1).
//
// The store's SQL is written once, in SQLite's spelling, and stays that way:
// with CCQUOTA_DB_URL unset nothing in this file changes a byte the store
// sends. A Postgres store gets there two ways, and every difference is one of
// them:
//
//   - the driver (pgConn below) rewrites what is purely lexical, for EVERY
//     statement: SQLite's `?` placeholders become `$1…$n`, and a Go bool
//     becomes 0/1 the way modernc's driver stores it. Nothing else is rewritten
//     there — a textual rewrite that understands SQL is a parser, and a parser
//     that is wrong only on the statement nobody tested is how a store writes
//     bad rows.
//   - everything that is not lexical — a function SQLite has and Postgres
//     spells differently (strftime, json_extract, min/max of two values), an
//     `INSERT OR IGNORE`, the catalog (PRAGMA, sqlite_master), the column
//     types of the DDL — is a method on dialect, called where the SQL is
//     written. Grep for `s.d.` / `d.` to find every one.
//
// New SQL goes through the same two roads (the EPIC's 共同约定 2): write it in
// SQLite's spelling, and wrap whatever only SQLite understands in a dialect
// method here, never an `if pg` beside the query.

import (
	"context"
	"database/sql"
	"database/sql/driver"
	"errors"
	"fmt"
	"os"
	"regexp"
	"strings"
	"sync"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/stdlib"
)

// dialect is which database a Store speaks to.
type dialect int

const (
	sqliteDialect dialect = iota
	postgresDialect
)

func (d dialect) pg() bool { return d == postgresDialect }

func (d dialect) String() string {
	if d.pg() {
		return "postgres"
	}
	return "sqlite"
}

// envDBURL names the Postgres connection string. Unset (the default, and
// production until the switch, EPIC #2119) = SQLite at the path Open is given.
const envDBURL = "CCQUOTA_DB_URL"

// dbURL is the Postgres connection string Open uses for a database at path, ""
// for SQLite. It is a variable for one reason: the Postgres leg of this
// package's tests gives each test's database file its own schema
// (pg_test.go), so a test that reopens "the same file" reopens the same data.
var dbURL = func(path string) string { return os.Getenv(envDBURL) }

// UsesPostgres says whether Open will open Postgres (CCQUOTA_DB_URL is set)
// rather than the SQLite file it is given.
func UsesPostgres() bool { return os.Getenv(envDBURL) != "" }

// isPostgresURL says whether s is a Postgres connection string.
func isPostgresURL(s string) bool {
	return strings.HasPrefix(s, "postgres://") || strings.HasPrefix(s, "postgresql://")
}

// ---- DDL ---------------------------------------------------------------

var (
	ddlIntPK   = regexp.MustCompile(`\bINTEGER\s+PRIMARY\s+KEY(\s+AUTOINCREMENT)?\b`)
	ddlInteger = regexp.MustCompile(`\bINTEGER\b`)
	ddlReal    = regexp.MustCompile(`\bREAL\b`)
	ddlBlob    = regexp.MustCompile(`\bBLOB\b`)
	ddlText    = regexp.MustCompile(`\bTEXT\b`)
	ddlComment = regexp.MustCompile(`--[^\n]*`)
)

// ddl is a CREATE / ALTER written for SQLite, in this dialect's column types.
//
// The schema stays written once (schema.sql, each table's const); this is the
// second set the issue asks for, derived rather than copied so the two cannot
// drift. Postgres:
//
//   - INTEGER is 64-bit in SQLite and 32-bit in Postgres: every one becomes
//     BIGINT (token counts and their sums pass 2^31 on a real hub).
//   - INTEGER PRIMARY KEY [AUTOINCREMENT] is SQLite's rowid alias, which fills
//     itself in on an insert that leaves it out: an identity column.
//   - REAL is 8 bytes in SQLite and 4 in Postgres: DOUBLE PRECISION.
//   - TEXT is compared byte by byte in SQLite (BINARY): COLLATE "C", so an
//     RFC 3339 timestamp, a key and an ORDER BY sort the same on both no matter
//     which locale the database was created with.
//
// Comments are dropped first so a word in one ("REAL money") is not rewritten
// into something a reader would trip over in \d+.
func (d dialect) ddl(s string) string {
	if !d.pg() {
		return s
	}
	s = ddlComment.ReplaceAllString(s, "")
	s = ddlIntPK.ReplaceAllString(s, "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
	s = ddlInteger.ReplaceAllString(s, "BIGINT")
	s = ddlReal.ReplaceAllString(s, "DOUBLE PRECISION")
	s = ddlBlob.ReplaceAllString(s, "BYTEA")
	s = ddlText.ReplaceAllString(s, `TEXT COLLATE "C"`)
	return s
}

// ---- functions and statements -------------------------------------------

// insertIgnore is an `INSERT OR IGNORE INTO …` statement in this dialect.
// Postgres has no OR IGNORE; ON CONFLICT DO NOTHING is the same thing for the
// only conflict the store relies on it for, a duplicate key.
func (d dialect) insertIgnore(q string) string {
	if !d.pg() {
		return q
	}
	i := strings.Index(q, "INSERT OR IGNORE INTO")
	if i < 0 {
		panic("insertIgnore: no INSERT OR IGNORE INTO in " + q)
	}
	return q[:i] + "INSERT INTO" + q[i+len("INSERT OR IGNORE INTO"):] + " ON CONFLICT DO NOTHING"
}

// hourOf is SQLite's strftime('%Y-%m-%dT%H:00:00Z', expr): the UTC hour an
// RFC 3339 timestamp falls in, as the rollup keys it.
func (d dialect) hourOf(expr string) string {
	if !d.pg() {
		return `strftime('%Y-%m-%dT%H:00:00Z', ` + expr + `)`
	}
	return `to_char((` + expr + `)::timestamptz AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24":00:00Z"')`
}

// timeFormat is strftime(pattern, expr) for a pattern the caller passes as the
// statement's argument: it hands back the expression and the argument to bind.
func (d dialect) timeFormat(pattern, expr string) (string, string) {
	if !d.pg() {
		return `strftime(?, ` + expr + `)`, pattern
	}
	r := strings.NewReplacer("%Y", "YYYY", "%m", "MM", "%d", "DD", "%H", "HH24", "%M", "MI", "%S", "SS", "T", `"T"`)
	return `to_char((` + expr + `)::timestamptz AT TIME ZONE 'UTC', ?)`, r.Replace(pattern)
}

// epochSeconds is a timestamp expression as seconds since 1970 — only ever
// used to order or subtract, so SQLite's julianday (days) and Postgres's epoch
// (seconds) are interchangeable wherever the caller compares two of them.
func (d dialect) epochSeconds(expr string) string {
	if !d.pg() {
		return `julianday(` + expr + `)`
	}
	return `EXTRACT(EPOCH FROM (` + expr + `)::timestamptz)`
}

// jsonText is json_extract(col, '$.key') for a scalar read as text.
func (d dialect) jsonText(col, key string) string {
	if !d.pg() {
		return `json_extract(` + col + `, '$.` + key + `')`
	}
	return `(NULLIF(` + col + `, '')::jsonb ->> '` + key + `')`
}

// updateIgnoreAccount is `UPDATE OR IGNORE <table> SET account_uuid = dst
// WHERE account_uuid = src`: a row whose move would collide with a row dst
// already holds stays where it is. key is the rest of the unique key
// account_uuid belongs to, which Postgres (no OR IGNORE) checks by hand.
func (d dialect) updateIgnoreAccount(table string, key []string, dst, src string) (string, []any) {
	if !d.pg() {
		return `UPDATE OR IGNORE ` + table + ` SET account_uuid = ? WHERE account_uuid = ?`, []any{dst, src}
	}
	match := make([]string, len(key))
	for i, k := range key {
		match[i] = `o.` + k + ` = ` + table + `.` + k
	}
	return `UPDATE ` + table + ` SET account_uuid = ? WHERE account_uuid = ?
		AND NOT EXISTS (SELECT 1 FROM ` + table + ` o WHERE o.account_uuid = ? AND ` + strings.Join(match, ` AND `) + `)`,
		[]any{dst, src, dst}
}

// least / greatest are SQLite's two-argument min() / max().
func (d dialect) least(a, b string) string {
	if !d.pg() {
		return `min(` + a + `, ` + b + `)`
	}
	return `LEAST(` + a + `, ` + b + `)`
}

func (d dialect) greatest(a, b string) string {
	if !d.pg() {
		return `max(` + a + `, ` + b + `)`
	}
	return `GREATEST(` + a + `, ` + b + `)`
}

// nocase is `expr COLLATE NOCASE` for an ORDER BY: ASCII case folded.
func (d dialect) nocase(expr string) string {
	if !d.pg() {
		return expr + ` COLLATE NOCASE`
	}
	return `lower(` + expr + `)`
}

// ---- catalog --------------------------------------------------------------

// querier is what the catalog reads need: a *sql.DB or a *sql.Tx.
type querier interface {
	Query(query string, args ...any) (*sql.Rows, error)
	QueryRow(query string, args ...any) *sql.Row
}

// tableExists says whether this database has a table called name.
func (d dialect) tableExists(q querier, name string) (bool, error) {
	var n int
	var err error
	if d.pg() {
		err = q.QueryRow(`SELECT COUNT(*) FROM pg_tables
			WHERE schemaname = current_schema() AND tablename = ?`, name).Scan(&n)
	} else {
		err = q.QueryRow(`SELECT COUNT(*) FROM sqlite_master WHERE type = 'table' AND name = ?`, name).Scan(&n)
	}
	return n > 0, err
}

// tables lists this database's tables, by name.
func (d dialect) tables(q querier) ([]string, error) {
	query := `SELECT name FROM sqlite_master WHERE type = 'table' AND name NOT LIKE 'sqlite_%' ORDER BY name`
	if d.pg() {
		query = `SELECT tablename FROM pg_tables WHERE schemaname = current_schema() ORDER BY tablename`
	}
	return scanStrings(q, query)
}

// columnInfo is one column of a table.
type columnInfo struct {
	name    string
	notNull bool
	pk      int // position in the primary key, 1-based; 0 = not in it
}

// columns lists table's columns in declaration order.
func (d dialect) columns(q querier, table string) ([]columnInfo, error) {
	var rows *sql.Rows
	var err error
	if d.pg() {
		// pg_catalog, not information_schema: the views join every constraint
		// in the database and take seconds once there are many tables.
		rows, err = q.Query(`
			SELECT a.attname, a.attnotnull,
			       COALESCE((SELECT array_position(c.conkey, a.attnum) FROM pg_constraint c
			                 WHERE c.conrelid = a.attrelid AND c.contype = 'p'), 0)
			FROM pg_attribute a
			WHERE a.attrelid = (SELECT c.oid FROM pg_class c
			                    WHERE c.relname = ? AND c.relnamespace = current_schema()::regnamespace)
			  AND a.attnum > 0 AND NOT a.attisdropped
			ORDER BY a.attnum`, table)
	} else {
		rows, err = q.Query(`SELECT name, "notnull", pk FROM pragma_table_info(?)`, table)
	}
	if err != nil {
		return nil, fmt.Errorf("inspect %s: %w", table, err)
	}
	defer rows.Close()
	var out []columnInfo
	for rows.Next() {
		var c columnInfo
		if err := rows.Scan(&c.name, &c.notNull, &c.pk); err != nil {
			return nil, err
		}
		out = append(out, c)
	}
	return out, rows.Err()
}

// foreignKey is one foreign key of a table: from (its columns) → table(to).
// An empty to[i] is "the parent's primary key" (SQLite leaves it out when the
// declaration did).
type foreignKey struct {
	table    string
	from, to []string
}

// foreignKeys lists child's foreign keys.
func (d dialect) foreignKeys(q querier, child string) ([]foreignKey, error) {
	var rows *sql.Rows
	var err error
	if d.pg() {
		rows, err = q.Query(`
			SELECT con.oid::bigint, pt.relname, ca.attname, pa.attname
			FROM pg_constraint con
			JOIN pg_class ct ON ct.oid = con.conrelid
			JOIN pg_namespace n ON n.oid = ct.relnamespace
			JOIN pg_class pt ON pt.oid = con.confrelid
			CROSS JOIN LATERAL unnest(con.conkey, con.confkey) WITH ORDINALITY AS k(c, p, i)
			JOIN pg_attribute ca ON ca.attrelid = con.conrelid AND ca.attnum = k.c
			JOIN pg_attribute pa ON pa.attrelid = con.confrelid AND pa.attnum = k.p
			WHERE con.contype = 'f' AND n.nspname = current_schema() AND ct.relname = ?
			ORDER BY con.oid, k.i`, child)
	} else {
		rows, err = q.Query(`SELECT id, "table", "from", COALESCE("to", '') FROM pragma_foreign_key_list(?) ORDER BY id, seq`, child)
	}
	if err != nil {
		return nil, fmt.Errorf("foreign keys of %s: %w", child, err)
	}
	defer rows.Close()
	var out []foreignKey
	last := int64(-1)
	for rows.Next() {
		var id int64
		var tbl, from, to string
		if err := rows.Scan(&id, &tbl, &from, &to); err != nil {
			return nil, err
		}
		if id != last || len(out) == 0 {
			out = append(out, foreignKey{table: tbl})
			last = id
		}
		fk := &out[len(out)-1]
		fk.from = append(fk.from, from)
		fk.to = append(fk.to, to)
	}
	return out, rows.Err()
}

func scanStrings(q querier, query string, args ...any) ([]string, error) {
	rows, err := q.Query(query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []string
	for rows.Next() {
		var s string
		if err := rows.Scan(&s); err != nil {
			return nil, err
		}
		out = append(out, s)
	}
	return out, rows.Err()
}

// ---- the Postgres driver ---------------------------------------------------

// openPostgres opens a pool on url through pgDriver. readOnly makes every
// transaction on it read-only, the Postgres spelling of SQLite's query_only
// pragma on the read pool.
func openPostgres(url string, readOnly bool) (*sql.DB, error) {
	cfg, err := pgx.ParseConfig(url)
	if err != nil {
		// pgx's message quotes the connection string, password and all.
		return nil, errors.New("parse " + envDBURL + ": not a valid postgres:// connection string")
	}
	// The simple protocol binds each argument by the Go value's own type, the
	// way SQLite takes whatever it is handed — the extended protocol would make
	// the server infer a type for `? IS NULL` and refuse it. pgx quotes the
	// values itself (standard_conforming_strings, which every supported
	// Postgres has on).
	cfg.DefaultQueryExecMode = pgx.QueryExecModeSimpleProtocol
	if readOnly {
		cfg.RuntimeParams["default_transaction_read_only"] = "on"
	}
	return sql.OpenDB(pgConnector{stdlib.GetConnector(*cfg)}), nil
}

type pgConnector struct{ base driver.Connector }

func (c pgConnector) Connect(ctx context.Context) (driver.Conn, error) {
	cn, err := c.base.Connect(ctx)
	if err != nil {
		return nil, err
	}
	return &pgConn{cn}, nil
}

func (c pgConnector) Driver() driver.Driver { return pgDriver{} }

// pgDriver exists so a *sql.DB can say which dialect it is (dialectOf).
type pgDriver struct{}

func (pgDriver) Open(string) (driver.Conn, error) {
	return nil, errors.New("store: the postgres driver opens through its connector")
}

// dialectOf is the dialect of a pool opened by this package.
func dialectOf(db *sql.DB) dialect {
	if _, ok := db.Driver().(pgDriver); ok {
		return postgresDialect
	}
	return sqliteDialect
}

// pgConn is pgx's connection, with each statement rebound first.
type pgConn struct{ driver.Conn }

func (c *pgConn) Prepare(query string) (driver.Stmt, error) {
	return c.PrepareContext(context.Background(), query)
}

// PrepareContext prepares nothing on the server: the statement is run as a
// fresh simple-protocol query each time, exactly like a direct Exec, so a
// prepared statement and an inline one can never disagree about types.
func (c *pgConn) PrepareContext(_ context.Context, query string) (driver.Stmt, error) {
	return &pgStmt{c: c, q: query}, nil
}

func (c *pgConn) ExecContext(ctx context.Context, query string, args []driver.NamedValue) (driver.Result, error) {
	args, err := pgArgs(args)
	if err != nil {
		return nil, err
	}
	return c.Conn.(driver.ExecerContext).ExecContext(ctx, rebind(query), args)
}

func (c *pgConn) QueryContext(ctx context.Context, query string, args []driver.NamedValue) (driver.Rows, error) {
	args, err := pgArgs(args)
	if err != nil {
		return nil, err
	}
	return c.Conn.(driver.QueryerContext).QueryContext(ctx, rebind(query), args)
}

func (c *pgConn) BeginTx(ctx context.Context, opts driver.TxOptions) (driver.Tx, error) {
	return c.Conn.(driver.ConnBeginTx).BeginTx(ctx, opts)
}

func (c *pgConn) Ping(ctx context.Context) error {
	if p, ok := c.Conn.(driver.Pinger); ok {
		return p.Ping(ctx)
	}
	return nil
}

func (c *pgConn) ResetSession(ctx context.Context) error {
	if r, ok := c.Conn.(driver.SessionResetter); ok {
		return r.ResetSession(ctx)
	}
	return nil
}

func (c *pgConn) IsValid() bool {
	if v, ok := c.Conn.(driver.Validator); ok {
		return v.IsValid()
	}
	return true
}

// CheckNamedValue takes every argument through database/sql's own default
// conversion (a pointer, a driver.Valuer, a named type), so pgArgs sees only
// the base types.
func (c *pgConn) CheckNamedValue(nv *driver.NamedValue) error {
	v, err := driver.DefaultParameterConverter.ConvertValue(nv.Value)
	if err != nil {
		return err
	}
	nv.Value = v
	return nil
}

type pgStmt struct {
	c *pgConn
	q string
}

func (s *pgStmt) Close() error  { return nil }
func (s *pgStmt) NumInput() int { return -1 }

func (s *pgStmt) Exec(args []driver.Value) (driver.Result, error) {
	return s.ExecContext(context.Background(), named(args))
}

func (s *pgStmt) Query(args []driver.Value) (driver.Rows, error) {
	return s.QueryContext(context.Background(), named(args))
}

func (s *pgStmt) ExecContext(ctx context.Context, args []driver.NamedValue) (driver.Result, error) {
	return s.c.ExecContext(ctx, s.q, args)
}

func (s *pgStmt) QueryContext(ctx context.Context, args []driver.NamedValue) (driver.Rows, error) {
	return s.c.QueryContext(ctx, s.q, args)
}

func named(args []driver.Value) []driver.NamedValue {
	out := make([]driver.NamedValue, len(args))
	for i, v := range args {
		out[i] = driver.NamedValue{Ordinal: i + 1, Value: v}
	}
	return out
}

// pgArgs stores a bool the way SQLite does — every flag column is an INTEGER
// holding 0 or 1, and Postgres will not put a boolean into one.
func pgArgs(args []driver.NamedValue) ([]driver.NamedValue, error) {
	for i := range args {
		if b, ok := args[i].Value.(bool); ok {
			if b {
				args[i].Value = int64(1)
			} else {
				args[i].Value = int64(0)
			}
		}
	}
	return args, nil
}

var rebound sync.Map // SQLite-spelled statement → Postgres-spelled

// rebind turns SQLite's positional `?` into Postgres's `$1…$n`, leaving any
// `?` inside a string literal, a quoted identifier or a comment alone.
func rebind(q string) string {
	if v, ok := rebound.Load(q); ok {
		return v.(string)
	}
	var b strings.Builder
	b.Grow(len(q) + 16)
	n := 0
	for i := 0; i < len(q); i++ {
		ch := q[i]
		switch {
		case ch == '\'' || ch == '"':
			j := i + 1
			for j < len(q) {
				if q[j] == ch {
					if j+1 < len(q) && q[j+1] == ch { // '' / "" escape
						j += 2
						continue
					}
					break
				}
				j++
			}
			if j >= len(q) {
				j = len(q) - 1
			}
			b.WriteString(q[i : j+1])
			i = j
		case ch == '-' && i+1 < len(q) && q[i+1] == '-':
			j := strings.IndexByte(q[i:], '\n')
			if j < 0 {
				j = len(q) - i - 1
			}
			b.WriteString(q[i : i+j+1])
			i += j
		case ch == '/' && i+1 < len(q) && q[i+1] == '*':
			j := strings.Index(q[i+2:], "*/")
			end := len(q) - 1
			if j >= 0 {
				end = i + 2 + j + 1
			}
			b.WriteString(q[i : end+1])
			i = end
		case ch == '?':
			n++
			fmt.Fprintf(&b, "$%d", n)
		default:
			b.WriteByte(ch)
		}
	}
	out := b.String()
	rebound.Store(q, out)
	return out
}
