package store

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestOpenPicksTheDialect is the degenerate case the EPIC (#2119 共同约定 1)
// asks every member to pin: with CCQUOTA_DB_URL unset the store is SQLite, in
// the file it was given; set, it is Postgres.
func TestOpenPicksTheDialect(t *testing.T) {
	path := filepath.Join(t.TempDir(), "hub.db")
	s, err := Open(path)
	if err != nil {
		t.Fatal(err)
	}
	defer s.Close()
	_, statErr := os.Stat(path)
	if os.Getenv(envDBURL) == "" {
		if s.d != sqliteDialect || dialectOf(s.write) != sqliteDialect || dialectOf(s.read) != sqliteDialect {
			t.Fatalf("no %s: dialect = %v, want sqlite", envDBURL, s.d)
		}
		if statErr != nil {
			t.Fatalf("no %s: the SQLite file was not created: %v", envDBURL, statErr)
		}
		return
	}
	if s.d != postgresDialect || dialectOf(s.write) != postgresDialect || dialectOf(s.read) != postgresDialect {
		t.Fatalf("%s set: dialect = %v, want postgres", envDBURL, s.d)
	}
	if statErr == nil {
		t.Fatalf("%s set: a SQLite file was created at %s anyway", envDBURL, path)
	}
	// The read pool is read-only on Postgres too, as query_only is on SQLite.
	if _, err := s.read.Exec(`INSERT INTO rollup_meta(key, value) VALUES('probe', '1')`); err == nil {
		t.Fatal("a write on the read pool went through")
	}
}

// TestSQLiteDialectChangesNothing: every dialect method hands SQLite back the
// exact SQL it was written with.
func TestSQLiteDialectChangesNothing(t *testing.T) {
	d := sqliteDialect
	for _, q := range []string{schemaSQL, `INSERT OR IGNORE INTO x VALUES(?)`, rollupInsertSQL, hourlyFoldSQL} {
		if d.ddl(q) != q || d.minMaxTS(q) != q {
			t.Errorf("sqlite rewrote %.40q", q)
		}
	}
	if got := d.insertIgnore(`INSERT OR IGNORE INTO x VALUES(?)`); got != `INSERT OR IGNORE INTO x VALUES(?)` {
		t.Errorf("insertIgnore = %q", got)
	}
	if got := d.hourOf("ts"); got != `strftime('%Y-%m-%dT%H:00:00Z', ts)` {
		t.Errorf("hourOf = %q", got)
	}
	if got := d.jsonText("details_json", "price_basis"); got != `json_extract(details_json, '$.price_basis')` {
		t.Errorf("jsonText = %q", got)
	}
	if q, args := d.updateIgnoreAccount("t", []string{"k"}, "dst", "src"); q != `UPDATE OR IGNORE t SET account_uuid = ? WHERE account_uuid = ?` || len(args) != 2 {
		t.Errorf("updateIgnoreAccount = %q %v", q, args)
	}
}

func TestRebind(t *testing.T) {
	for in, want := range map[string]string{
		`SELECT ? , ?`:                          `SELECT $1 , $2`,
		`SELECT '?' , ? -- what?` + "\n" + `,?`: `SELECT '?' , $1 -- what?` + "\n" + `,$2`,
		`SELECT 'it''s ?', "q?", ? /* ? */ , ?`: `SELECT 'it''s ?', "q?", $1 /* ? */ , $2`,
		`SELECT json ->> '$.a' WHERE x = ?`:     `SELECT json ->> '$.a' WHERE x = $1`,
		`no placeholders`:                       `no placeholders`,
	} {
		if got := rebind(in); got != want {
			t.Errorf("rebind(%q)\n = %q\nwant %q", in, got, want)
		}
	}
}

func TestPostgresDDL(t *testing.T) {
	got := postgresDialect.ddl(`CREATE TABLE t (
  id INTEGER PRIMARY KEY AUTOINCREMENT, -- REAL money, in a comment
  n  INTEGER NOT NULL DEFAULT 0,
  c  REAL,
  b  BLOB,
  s  TEXT NOT NULL DEFAULT ''
);`)
	for _, want := range []string{
		`id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,`,
		`n  BIGINT NOT NULL DEFAULT 0`,
		`c  DOUBLE PRECISION`,
		`b  BYTEA`,
		`s  TEXT COLLATE "C" NOT NULL DEFAULT ''`,
	} {
		if !strings.Contains(got, want) {
			t.Errorf("ddl lacks %q:\n%s", want, got)
		}
	}
	if strings.Contains(got, "REAL money") {
		t.Errorf("a comment survived into the DDL:\n%s", got)
	}
	if got := postgresDialect.insertIgnore(`INSERT OR IGNORE INTO x VALUES(?)`); got != `INSERT INTO x VALUES(?) ON CONFLICT DO NOTHING` {
		t.Errorf("insertIgnore = %q", got)
	}
}
